# Generated by Django 2.2.4 on 2020-03-06 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('felicia_app', '0002_order_orderupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='static/images')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.CreateModel(
            name='subcatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcatagory', models.CharField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='static/images')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='felicia_app.catagory')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='catagory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='felicia_app.catagory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='subcatagory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='felicia_app.subcatagory'),
            preserve_default=False,
        ),
    ]
