# Generated by Django 2.2.4 on 2020-03-06 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('felicia_app', '0004_auto_20200306_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='catagory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='catagory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcatagory',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='catagory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='subcatagory',
            new_name='subcategory',
        ),
    ]
