# Generated by Django 3.0.3 on 2020-03-18 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('felicia_app', '0007_auto_20200318_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='felicia_app.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AddField(
            model_name='product',
            name='pub_date',
            field=models.DateField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='felicia_app.subcategory'),
            preserve_default=False,
        ),
    ]
